version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test
      - npm run deploy

artifacts:
  files:
    - "**/*"
  base-directory: build
  name: react-artifacts
