pipeline_bucket_name = "your_pipeline_bucket_name"
repo_branch = "your_repo_branch"
repo_name = "your_repo_name"
repo_owner = "your_repo_owner"
website_bucket_name = "your_website_bucket_name"
repo_token = "your_repo_token"